title: Just the Docs Exercise
description: An exercise to use Just the Docs theme.
theme: just-the-docs
color_scheme: custom_style

url: https://diana-t1.github.io/JTD_Exercise

aux_links:
  Template Repository: https://github.com/diana-t1/JTD_Exercise


